# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 228c120fc4b042fd956a703da105b8b21d5fcd24db3f19b2d34dd6f8a06dd9ae70a380c562150cfe92552f98f91ee9b4b84255409782b9c4ebde7a249b67735d

test:
  secret_key_base: 095a83bbaa318aff743cd08a8b513618c8f2ff5cb38bc9473df68d8c37fcc4d6daa0cae8254bddf8113dc0bab4f58dcb33f9e91e13b24404808728a1ed705ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
